main: com.mythicacraft.teleportledger.TeleportLedger
name: TeleportLedger
version: 1.1
author: rockjolt375
depend: [Vault]
description: Allows use of teleportation in the form of currency
commands:
    tptokens:
        usage: /tptokens [player]
    tpa:
        usage: /tpa <player>
    tpahere:
        usage: /tpahere <player>
    call:
        usage: /call <player>
    tpask:
        usage: /tpask <player>
    tpignoreall:
        usage: /tpignoreall
    tpblock:
        usage: /tpblock <player>
    tpunblock:
        usage: /tpunblock <player>
    tpaccept:
        usage: /tpaccept
    tpdeny:
        usage: /tpdeny
    back:
        usage: /back
permissions: 
    teleportledger.use:
        description: Allows usage of the teleportation ledger
        default: true
    teleportledger.exempt:
        description: Allows group exemption from ledger counts
    teleportledger.mod:
        description: Allows mods to view other players token count
        default: op
        children:
            teleportledger.use: true